DROP TABLE DISCOUNT;
DROP TABLE INVOICE;
DROP TABLE LENT_BOOK;
DROP TABLE BOOK;
DROP TABLE "USER";
DROP TABLE SECTION;
DROP TABLE PARTNER;
DROP SEQUENCE PARTNER_ID_SEQ;
DROP SEQUENCE SECTION_ID_SEQ;
DROP SEQUENCE USER_ID_SEQ;
DROP SEQUENCE BOOK_ID_SEQ;
DROP SEQUENCE INVOICE_ID_SEQ;

CREATE SEQUENCE PARTNER_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 9999;
   
CREATE SEQUENCE SECTION_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 9999; 
    
CREATE SEQUENCE USER_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 9999;
    
CREATE SEQUENCE BOOK_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 9999;

CREATE SEQUENCE INVOICE_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 9999;

CREATE TABLE PARTNER(
    PARTNER_ID NUMBER(4),
    NUM_OF_LOGINS NUMBER(4),
    PARTNER_NAME VARCHAR2(50) CONSTRAINT PARTNER_NAME_NN NOT NULL,
    PARTNER_PASS VARCHAR2(50) CONSTRAINT PARTNER_PASS_NN NOT NULL,
    PARTNER_EMAIL VARCHAR2(50) CONSTRAINT PARTNER_EMAIL_NN NOT NULL,
    CONSTRAINT PARTNER_EMAIL_U UNIQUE (PARTNER_EMAIL),
    CONSTRAINT PARTNER_ID_PK PRIMARY KEY(PARTNER_ID)
);

CREATE TABLE SECTION(
    SECTION_ID NUMBER(4),
    SECTION_NAME VARCHAR2(50) CONSTRAINT SECTION_NAME_NN NOT NULL,
    CONSTRAINT SECTION_NAME_U UNIQUE (SECTION_NAME),
    CONSTRAINT SECTION_ID_PK PRIMARY KEY(SECTION_ID)
);
    
CREATE TABLE "USER"(
    USER_ID NUMBER(4),
    NUM_OF_LOGINS NUMBER(4),
    USER_NAME VARCHAR2(50) CONSTRAINT USER_NAME_NN NOT NULL,
    USER_PASS VARCHAR2(50) CONSTRAINT USER_PASS_NN NOT NULL,
    USER_EMAIL VARCHAR2(50) CONSTRAINT USER_EMAIL_NN NOT NULL,
    CONSTRAINT USER_EMAIL_U UNIQUE (USER_EMAIL),
    CONSTRAINT USER_ID_PK PRIMARY KEY(USER_ID)
);
    
CREATE TABLE BOOK(
    BOOK_ID NUMBER(4),
    AUTHOR VARCHAR2(50) CONSTRAINT AUTHOR_NN NOT NULL,
    TITLE VARCHAR2(50) CONSTRAINT TITLE_NN NOT NULL,
    "DESCRIPTION" VARCHAR2(100) CONSTRAINT DESCRIPTION_NN NOT NULL,
    IS_LENT VARCHAR2(5) CONSTRAINT IS_LENT_NN NOT NULL,
    SECTION_ID NUMBER(4),
    PARTNER_ID NUMBER(4),
    CONSTRAINT BOOK_ID_PK PRIMARY KEY(BOOK_ID),
    CONSTRAINT BOOK_AUTHOR_TITLE_U UNIQUE (AUTHOR, TITLE),
    CONSTRAINT BOOK_SECTION_ID_FK FOREIGN KEY(SECTION_ID) REFERENCES SECTION(SECTION_ID) ON DELETE CASCADE,
    CONSTRAINT BOOK_PARTNER_ID_FK FOREIGN KEY(PARTNER_ID) REFERENCES PARTNER(PARTNER_ID) ON DELETE CASCADE
);
    
CREATE TABLE LENT_BOOK(
    BOOK_ID NUMBER(4),
    AUTHOR VARCHAR2(50) CONSTRAINT LB_AUTHOR_NN NOT NULL,
    TITLE VARCHAR2(50) CONSTRAINT LB_TITLE_NN NOT NULL,
    "DESCRIPTION" VARCHAR2(50) CONSTRAINT LB_DESCRIPTION_NN NOT NULL,
    ISSUED_DATE VARCHAR2(12) CONSTRAINT ISSUED_DATE_NN NOT NULL,
    DAYS_FROM_ISSUE NUMBER(2) CONSTRAINT DAYS_FROM_ISSUE_NN NOT NULL,
    RETURN_DATE VARCHAR2(12),
    IS_LENT VARCHAR2(5) CONSTRAINT LB_IS_LENT_NN NOT NULL,
    SECTION_ID NUMBER(4),
    PARTNER_ID NUMBER(4),
    USER_ID NUMBER(4),
    PRICE NUMBER(6, 2),
    EXCEEDED_DAYS NUMBER(3),
    EXCEEDED_PRICE NUMBER(6, 2),
    CONSTRAINT LENT_BOOK_PK PRIMARY KEY(BOOK_ID, ISSUED_DATE),
    CONSTRAINT LENT_BOOK_SECTION_ID_FK FOREIGN KEY(SECTION_ID) REFERENCES SECTION(SECTION_ID) ON DELETE CASCADE,
    CONSTRAINT LENT_BOOK_PARTNER_ID_FK FOREIGN KEY(PARTNER_ID) REFERENCES PARTNER(PARTNER_ID) ON DELETE CASCADE,
    CONSTRAINT LENT_BOOK_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES "USER"(USER_ID) ON DELETE CASCADE,
    CONSTRAINT LENT_BOOK_BOOK_ID_FK FOREIGN KEY(BOOK_ID) REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE
);
    
CREATE TABLE INVOICE(
    INVOICE_ID NUMBER(4),
    INVOICE_DATE VARCHAR2(12) CONSTRAINT INVOICE_DATE_NN NOT NULL,
    USER_ID NUMBER(4),
    CARD_OR_CASH VARCHAR2(5) CONSTRAINT CARD_OR_CASH_NN NOT NULL,
    DISCOUNT VARCHAR2(5) CONSTRAINT DISCOUNT_NN NOT NULL,
    CONSTRAINT INVOICE_ID_PK PRIMARY KEY(INVOICE_ID),
    CONSTRAINT INVOICE_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES "USER"(USER_ID) ON DELETE CASCADE
);

CREATE TABLE DISCOUNT(
    CODE VARCHAR2(12),
    EXP_DATE VARCHAR2(12) CONSTRAINT EXP_DATE_NN NOT NULL,
    USER_ID NUMBER(4),
    IS_USED VARCHAR2(5) CONSTRAINT IS_USED_NN NOT NULL,
    CONSTRAINT DISCOUNT_CODE_PK PRIMARY KEY(CODE),
    CONSTRAINT DISCOUNT_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES "USER"(USER_ID) ON DELETE CASCADE
); 
    
INSERT INTO PARTNER VALUES(PARTNER_ID_SEQ.NEXTVAL, 0, 'Lily White', 'lily.white1', 'lily.white1@yahoo.com');
INSERT INTO PARTNER VALUES(PARTNER_ID_SEQ.NEXTVAL, 2, 'Jonathan Graham', 'Graham02#', 'john_graham@gmail.com');
INSERT INTO PARTNER VALUES(PARTNER_ID_SEQ.NEXTVAL, 1, 'Violet Riley', 'Violet03#', 'violetRiley33@yahoo.com');
INSERT INTO PARTNER VALUES(PARTNER_ID_SEQ.NEXTVAL, 1, 'Susan Harris', 'Susan04#', 'SusanHarrys@gmail.com');

INSERT INTO SECTION VALUES(SECTION_ID_SEQ.NEXTVAL, 'classics');
INSERT INTO SECTION VALUES(SECTION_ID_SEQ.NEXTVAL, 'allegories');
INSERT INTO SECTION VALUES(SECTION_ID_SEQ.NEXTVAL, 'science fiction');
INSERT INTO SECTION VALUES(SECTION_ID_SEQ.NEXTVAL, 'dystopian');
INSERT INTO SECTION VALUES(SECTION_ID_SEQ.NEXTVAL, 'fantasy');
INSERT INTO SECTION VALUES(SECTION_ID_SEQ.NEXTVAL, 'horror');
INSERT INTO SECTION VALUES(SECTION_ID_SEQ.NEXTVAL, 'comedy');

INSERT INTO "USER" VALUES(USER_ID_SEQ.NEXTVAL, 0, 'Belle Garcia', 'BelleGarcia1', 'BelleGarcia1@yahoo.com');
INSERT INTO "USER" VALUES(USER_ID_SEQ.NEXTVAL, 1, 'Daniel Roberts', 'Roberts02#', 'danielRoberts2@gmail.com');
INSERT INTO "USER" VALUES(USER_ID_SEQ.NEXTVAL, 1, 'Denise Cole', 'Denise03#', 'denise_cole3@gmail.com');
INSERT INTO "USER" VALUES(USER_ID_SEQ.NEXTVAL, 2, 'Ryan Ford', 'FordRyan04#', 'ryan.ford4@yahoo.com');
INSERT INTO "USER" VALUES(USER_ID_SEQ.NEXTVAL, 3, 'Dennis Fox', 'Dennis05#', 'dennisFox5@yahoo.com');

INSERT INTO BOOK VALUES(BOOK_ID_SEQ.NEXTVAL, 'Frank Herbert', 'Dune', 'science fiction', 'FALSE', 3, 2);
INSERT INTO BOOK VALUES(BOOK_ID_SEQ.NEXTVAL, 'F. Scott Fitzgerald', 'The Great Gatsby', 'classic novel', 'TRUE', 1, 2);
INSERT INTO BOOK VALUES(BOOK_ID_SEQ.NEXTVAL, 'Ray Bradbury', 'Fahrenheit 451', 'dystopian novel', 'FALSE', 4, 3);
INSERT INTO BOOK VALUES(BOOK_ID_SEQ.NEXTVAL, 'George Orwell', 'Animal Farm', 'allegory', 'FALSE', 2, 3);
INSERT INTO BOOK VALUES(BOOK_ID_SEQ.NEXTVAL, 'George Orwell', '1984', 'dystopian novel', 'TRUE', 4, 3);
INSERT INTO BOOK VALUES(BOOK_ID_SEQ.NEXTVAL, 'Jane Austen', 'Pride and Prejudice', 'classic novel', 'TRUE', 1, 3);
INSERT INTO BOOK VALUES(BOOK_ID_SEQ.NEXTVAL, 'Mary Shelley', 'Frankenstein', 'horror', 'FALSE', 6, 4);
INSERT INTO BOOK VALUES(BOOK_ID_SEQ.NEXTVAL, 'Harper Lee', 'To Kill a Mockingbird', 'classic novel', 'TRUE', 1, 4);
INSERT INTO BOOK VALUES(BOOK_ID_SEQ.NEXTVAL, 'J. K. Rowling', 'Harry Potter and the Philosopher Stone', 'fantasy', 'TRUE', 5, 4);
INSERT INTO BOOK VALUES(BOOK_ID_SEQ.NEXTVAL, 'Stephen King', 'The Shining', 'horror', 'TRUE', 6, 4);
INSERT INTO BOOK VALUES(BOOK_ID_SEQ.NEXTVAL, 'Leigh Bardugo', 'Six of Crows', 'fantasy', 'FALSE', 5, 4);

INSERT INTO LENT_BOOK VALUES(2, 'F. Scott Fitzgerald', 'The Great Gatsby', 'classic novel', '2022-05-04', 20, NULL, 'TRUE', 1, 2, 3, NULL, NULL, NULL);
INSERT INTO LENT_BOOK VALUES(5, 'George Orwell', '1984', 'dystopian novel', '2022-05-14', 12, NULL, 'TRUE', 4, 3, 4, NULL, NULL, NULL);
INSERT INTO LENT_BOOK VALUES(6, 'Jane Austen', 'Pride and Prejudice', 'classic novel', '2022-05-20', 10, NULL, 'TRUE', 1, 3, 3, NULL, NULL, NULL);
INSERT INTO LENT_BOOK VALUES(8, 'Harper Lee', 'To Kill a Mockingbird', 'classic novel', '2022-05-23', 11, NULL, 'TRUE', 1, 4, 5, NULL, NULL, NULL);
INSERT INTO LENT_BOOK VALUES(10, 'Stephen King', 'The Shining', 'horror', '2022-05-07', 22, NULL, 'TRUE', 6, 4, 3, NULL, NULL, NULL);
INSERT INTO LENT_BOOK VALUES(9, 'J. K. Rowling', 'Harry Potter and the Philosopher Stone', 'fantasy', '2022-05-12', 14, NULL, 'TRUE', 5, 4, 4, NULL, NULL, NULL);
    
INSERT INTO INVOICE VALUES(INVOICE_ID_SEQ.NEXTVAL, '2022-05-04', 3, 'card', 'FALSE');
INSERT INTO INVOICE VALUES(INVOICE_ID_SEQ.NEXTVAL, '2022-05-07', 3, 'card', 'FALSE');
INSERT INTO INVOICE VALUES(INVOICE_ID_SEQ.NEXTVAL, '2022-05-12', 4, 'cash', 'FALSE');
INSERT INTO INVOICE VALUES(INVOICE_ID_SEQ.NEXTVAL, '2022-05-14', 4, 'card', 'FALSE');
INSERT INTO INVOICE VALUES(INVOICE_ID_SEQ.NEXTVAL, '2022-05-20', 3, 'cash', 'FALSE');
INSERT INTO INVOICE VALUES(INVOICE_ID_SEQ.NEXTVAL, '2022-05-23', 5, 'card', 'FALSE');
